extends: ["spectral:oas"]
formats: ["json"]
functionsDir: "./spectral-functions"
rules:
  schema-required-title:
    description: Schema must have a title
    message: "{{error}}: Schema must include a title to clearly identify its purpose"
    given: "$"
    severity: error
    recommended: true
    then:
      field: title
      function: truthy
  
  schema-required-description:
    description: Schema should have a description
    message: "{{error}}: Schema should include a description explaining its purpose and usage"
    given: "$"
    severity: warn
    recommended: true
    then:
      field: description
      function: truthy